# Values for the test chart
replicaCount: 1

image:
  repository: nginx
  tag: alpine

secrets:
  # These will be replaced by AVP from Vault
  username: <secret>
  password: <secret>
  database_url: <secret>
